apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: ckan

helmCharts:
  - name: ckan
    namespace: ckan
    releaseName: ckan
    repo: https://keitaro-charts.storage.googleapis.com
    valuesFile: values.yaml
    includeCRDs: true
    version: 1.0.1
    
resources:
  - namespace.yaml