apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k6

bases:
  - ../../../base

configMapGenerator:
  - name: k6-settings
    literals:
    - FLOW=dev_get_1u_1s
    - RESOURCE_ID=1dc21a11-78bc-49ee-8c6c-a27ab76285da

secretGenerator:
  - name: k6-secret
    envs:
      - .k6.env
  - name: minio-secret
    envs:
      - .minio.env
    behavior: replace