apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k6

commonLabels:
  base: k6

images:
  - name: k6-release-image
    newName: loadimpact/k6
    newTag: 0.34.1

configMapGenerator:
  - name: k6-scripts
    files:
      - ../../../k6/datenhub_rest_get_1u_1s.js
      - ../../../k6/omi_ckan_get_1u_1s.js
      - ../../../k6/omi_ckan_post_1u_1s.js
      - ../../../k6/testhub_ckan_get_1u_1s.js
      - ../../../k6/testhub_ckan_post_1u_1s.js
      - ../../../k6/testhub_ckan_post-update_1u_1s.js
      - ../../../k6/testhub_rest_get_1u_1s.js
      - ../../../k6/testhub_rest_post_1u_1s.js
      - ../../../k6/testhub_rest_post_1u_Xs.js
      - ../../../k6/helper.js
      - ../../../k6/dump.csv
  - name: k6-run
    files:
      - run.sh

secretGenerator:
  - name: minio-secret
    literals:
      - MC_HOST_k6=https://Q3AM3UQ867SPQQA43P2F:zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG@play.min.io


resources:
  - deployment.yaml
